//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabrielBargas.Clientes.Database.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.ENDERECO = new HashSet<ENDERECO>();
            this.HISTORICO_RELACIONAMENTO = new HashSet<HISTORICO_RELACIONAMENTO>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string NOME { get; set; }
        public string CPF_CNPJ { get; set; }
        public string TEL_PRINCIPAL { get; set; }
        public string TEL_ALTERNATIVO { get; set; }
        public string CLASSIFICACAO { get; set; }
        public Nullable<int> ID_SEGMENTO { get; set; }
    
        public virtual SEGMENTO SEGMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENDERECO> ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_RELACIONAMENTO> HISTORICO_RELACIONAMENTO { get; set; }
    }
}
