//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabrielBargas.Clientes.Database.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENDERECO
    {
        public int ID_ENDERECO { get; set; }
        public string ESTADO { get; set; }
        public string CIDADE { get; set; }
        public string CEP { get; set; }
        public string RUA { get; set; }
        public int NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string TIPO_ENDERECO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
