//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabrielBargas.Clientes.Database.Banco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GABRIELBARGASEntities : DbContext
    {
        public GABRIELBARGASEntities()
            : base("name=GABRIELBARGASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<ENDERECO> ENDERECO { get; set; }
        public virtual DbSet<HISTORICO_RELACIONAMENTO> HISTORICO_RELACIONAMENTO { get; set; }
        public virtual DbSet<SEGMENTO> SEGMENTO { get; set; }
    }
}
