//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabrielBargas.Clientes.Database.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_RELACIONAMENTO
    {
        public int ID_HISTORICO_RELACIONAMENTO { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DATA_HISTORICO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
