USE GABRIELBARGAS
GO
INSERT INTO SEGMENTO(DESCRICAO)VALUES('VAREJO')
GO
INSERT INTO SEGMENTO(DESCRICAO)VALUES('TECNOLOGIA')
GO
INSERT INTO SEGMENTO(DESCRICAO)VALUES('COSMEDICO')
GO
INSERT INTO SEGMENTO(DESCRICAO)VALUES('ALIMENTOS')