CREATE DATABASE GABRIELBARGAS
GO
USE GABRIELBARGAS
GO
CREATE TABLE SEGMENTO(
ID_SEGMENTO INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(100) NOT NULL
)
GO
CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY IDENTITY,
NOME VARCHAR(150) NOT NULL,
CPF_CNPJ CHAR(14),
TEL_PRINCIPAL CHAR(11) NOT NULL,
TEL_ALTERNATIVO CHAR(11),
CLASSIFICACAO CHAR(1),
FLAG_INATIVO BIT,
ID_SEGMENTO INT FOREIGN KEY REFERENCES SEGMENTO(ID_SEGMENTO)
)
GO
CREATE TABLE ENDERECO(
ID_ENDERECO INT PRIMARY KEY IDENTITY,
ESTADO CHAR(2) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
CEP CHAR(8) NOT NULL,
RUA VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL,
COMPLEMENTO VARCHAR(50),
TIPO_ENDERECO CHAR(1) NOT NULL,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE)
)
GO
CREATE TABLE HISTORICO_RELACIONAMENTO(
ID_HISTORICO_RELACIONAMENTO INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(MAX) NOT NULL,
DATA_HISTORICO DATETIME NOT NULL,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE)
)
